cart/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:p_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:p_id>/", views.cart_remove, name="cart_remove"),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = "coupons"
urlpatterns = [
    path("apply/", views.coupon_apply, name="apply"),
    path("remove/", views.remove_coupon, name="remove"),
]

data/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from .views import home
from . import views
from django.urls import path, include, re_path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", home, name="home"),
    path("account/", include("account.urls")),
    re_path(
        r"^account/account/$", RedirectView.as_view(url="/account/", permanent=True)
    ),
    path("orders/", include("orders.urls", namespace="orders")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("", include("shop.urls", namespace="shop")),
    # path('account/', views.account_details, name='account_details'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    # path('', views.user_orders, name="user_orders"),
    path("create/", views.order_create, name="order_create"),
    path("order/created/<int:order_id>/", views.order_created, name="order_created"),
    path('admin/order/<int:order_id>/pdf/',views.admin_order_pdf,name='admin_order_pdf'),
    path('user_orders/', views.user_orders, name='user_orders'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path('', views.product_list, name="product_list"),
    path('<str:category_name>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail')
]

cart/models.py
# models.py
from django.contrib.auth.models import User
from django.db import models
from shop.models import Product
from coupons.models import Coupon


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through="CartItem")
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"Cart for {self.user.username}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0, blank=True)

    def total_price(self):
        print(self.product.discount)
        if self.product.discount:
            return self.quantity * self.product.discounted_price
        else:
            return self.quantity * self.product.price

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        required=False,
        widget=forms.Select(attrs={"class": "form-control-sm"}),
    )
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .models import CartItem
from .cart import CartWrapper
from .forms import CartAddProductForm
from django.contrib import messages
from coupons.forms import CouponApplyForm
from django.contrib.auth.decorators import login_required


# Create your views here.


@login_required
@require_POST
def cart_add(request, p_id):
    user = request.user
    cart = CartWrapper(user)
    product = get_object_or_404(Product, p_id=p_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        if product.stock < cd["quantity"]:
            messages.error(
                request,
                f"Sorry, {product.product_name} stock is less than requested.",
                extra_tags="danger",
            )
            return redirect("shop:product_list")

        cart.add(
            product=product,
            quantity=cd["quantity"],
            override_quantity=cd["override"],
        )

        product.stock -= cd["quantity"]

        product.save()
        messages.success(
            request, f"{product.product_name} added to your cart successfully."
        )
    return redirect("cart:cart_detail")


@login_required
@require_POST
def cart_remove(request, p_id):
    user = request.user
    cart = CartWrapper(user)
    product = get_object_or_404(Product, p_id=p_id)
    cart_items = CartItem.objects.filter(cart=cart.cart)
    for item in cart_items:
        if product == item.product:
            quantity = item.quantity
            cart.remove(product)

            # Add the removed quantity back to the product's stock
            product.stock += quantity
            product.save()

            messages.success(
                request, f"{product.product_name} removed from your cart successfully."
            )
            return redirect("cart:cart_detail")

    messages.error(
        request, f"{product.product_name} is not in your cart.", extra_tags="danger"
    )

    return redirect("cart:cart_detail")


@login_required
def cart_detail(request):
    user = request.user
    cart = CartWrapper(user)
    coupon_apply_form = CouponApplyForm()
    return render(
        request,
        "cart/detail.html",
        {"cart": cart, "coupon_apply_form": coupon_apply_form},
    )

templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
{% load mathfilters %}

Your shopping cart
{% endblock %}
{% block content %}
<h1>Your shopping cart</h1>
<div class="container mt-4 ml-3">
   <table class="table table-bordered table-striped">
      <thead>
         <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
         </tr>
      </thead>
      <tbody>
         {% for item in cart %}
         {% with product=item.product %}
         <tr>
            <td>
               <a href="{{ product.get_absolute_url }}">
               <img style="max-height: 100px;" src="{% if product.p_image %} {{ product.p_image }}
               {% else %}{% static "img/no_image.png" %}{% endif %}">
               </a>
            </td>
            <td>{{ product.product_name }}</td>
            <td>
               <form action="{% url "cart:cart_add" product.p_id %}" method="post">
               {{ item.update_quantity_form.quantity }}
               {{ item.update_quantity_form.override }}
               <button type="submit" class="btn btn-primary">Update</button>
               {% csrf_token %}
               </form>
            </td>
            <td>
               <form action="{% url "cart:cart_remove" product.p_id %}" method="post">
               <button type="submit" class="btn btn-danger">Remove</button>
               {% csrf_token %}
               </form>
            </td>
            <td class="num">
               {% if product.discount %}
                  EGP {{ product.discounted_price|floatformat:2 }}
                  {% else %}
                  EGP {{ item.price }}
               {% endif %}
            </td>
            <td class="num">EGP {{ item.total_price | floatformat:2 }}</td>
         </tr>
         {% endwith %}
         {% endfor %}
          {% if cart.coupon %}
            <tr class="subtotal">
              <td>Subtotal</td>
              <td colspan="4"></td>
              <td class="num">EGP {{ cart.get_total_price|floatformat:2 }}</td>
            </tr>
            <tr>
              <td>
                "{{ cart.coupon.code }}" coupon
                ({{ cart.coupon.discount }}% off)
              </td>
              <td colspan="4"></td>
              <td class="num neg">
                - EGP {{ cart.get_discount|floatformat:2 }}
              </td>
            </tr>
          {% endif %}
          <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">
              EGP {{ cart.get_total_price_after_discount|floatformat:2 }}
            </td>
          </tr>
      </tbody>
   </table>
</div>
{% if cart|length > 0 %}
<div class="card">
    <div class="card-body">
        <p class="card-text">Apply a coupon:</p>

        {% if cart.coupon %}
            <p>Your current coupon: {{ cart.coupon.code }} ({{ cart.coupon.discount }}% off)</p>
        {% else %}
            <form action="{% url "coupons:apply" %}" method="post" class="d-inline">
                {{ coupon_apply_form|crispy }}
                <input type="submit" value="Apply" class="btn btn-success">
                {% csrf_token %}
            </form>
        {% endif %}

        {% if cart.coupon %}
            <form method="post" action="{% url 'coupons:remove' %}" class="d-inline">
                {% csrf_token %}
                <input type="submit" value="Remove Coupon" class="btn btn-danger" >
            </form>
        {% endif %}
    </div>
</div>


<p class="text-right">
   <a href="{% url "shop:product_list" %}" class="btn btn-primary">Continue shopping</a>
   <a href="{% url "orders:order_create" %}" class="btn btn-success">Checkout</a>
</p>
{% else %}
<p>Your cart is empty.</p>
<a href="{% url "shop:product_list" %}" class="button light">Continue shopping</a>
{% endif %}
{% endblock %}

templates/cart/details.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}
  <h1>Your shopping cart</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "cart:cart_remove" product.id %}" method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button
    light">Continue shopping</a>
    <a href="{% url "orders:order_create" %}" class="button">Checkout</a>
  </p>
{% endblock %}