cart/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:p_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:p_id>/", views.cart_remove, name="cart_remove"),
]

data/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from .views import home
from . import views
from django.urls import path, include, re_path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", home, name="home"),
    path("account/", include("account.urls")),
    re_path(
        r"^account/account/$", RedirectView.as_view(url="/account/", permanent=True)
    ),
    path("orders/", include("orders.urls", namespace="orders")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("", include("shop.urls", namespace="shop")),
    # path('account/', views.account_details, name='account_details'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    # path('', views.user_orders, name="user_orders"),
    path("create/", views.order_create, name="order_create"),
    path("order/created/<int:order_id>/", views.order_created, name="order_created"),
    path('admin/order/<int:order_id>/pdf/',views.admin_order_pdf,name='admin_order_pdf'),
    path('user_orders/', views.user_orders, name='user_orders'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path('', views.product_list, name="product_list"),
    path('<str:category_name>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.css" %}" />
    <link rel="stylesheet" href="{% static "css/CSS/base.css" %}" />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto"
      rel="stylesheet"
    />
    <link rel="icon" href="{% static 'logoo.png' %}">

  </head>
  <body>
        <nav class="navbar bg-dark navbar-expand-lg bg-dark sticky-top" data-bs-theme="dark">
            <div class="container-fluid">
                <img src="{% static 'logoo.png' %}" class="logo-img">
                <a class="navbar-brand" style="font-size: 2em; font-family: Fasthand" href="{% url 'shop:product_list' %}">GroceryGo</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">

                    <div class="navbar-nav ms-auto">
                            <a class="nav-link {% if 'shop' in request.path %}active{% endif %}" href="{% url "shop:product_list" %}">Products</a>
                            <a class="nav-link {% if 'order' in request.path %}active{% endif %}" href="{% url "orders:user_orders" %}">Orders</a>                 
                            <p>
                                <a href="{% url "cart:cart_detail" %}" class="btn btn-success d-inline-flex" style="margin-top: 12px; margin-right: 32px">
                                    <i class="bi bi-cart" style="margin-right: 5px;"></i> Cart <span class="badge text-bg-secondary" style="margin-left:10px">{{cart|length}}</span></a>
                                </a>
                            </p>
                            
                            <p class="d-inline-flex" style="margin-top: 12px">
                                <button class="btn btn-light search-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                                    Search
                                </button>
                            </p>
                </div>
                <div class="navbar-nav ms-auto">
                <div class="dropdown m-10">
                    {% if user.is_authenticated %}
                    <a href="#" class="nav-link d-block link-light text-decoration-none user-name dropdown-toggle"  id="dropdownUser1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Hello, {{ user.username }}
                    </a>
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item" href="{% url 'account'%}">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'password_change'%}">Change password</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                    </ul>
                    {% else %}
                    <div class="navbar-nav mr-auto">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </div>
                    {% endif %}
                </div>
                </div>

            </div>
        </nav>
        <div class="collapse" id="collapseExample">
            <div class="card card-body">
               {% include 'search_form.html' %}
            </div>
        </div>
        {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
        {% endif %}
    <div id="content" class="container-fluid">
      <div class="row">{% block content %}{% endblock %}</div>
    </div>

    <script src="{% static "bootstrap/js/bootstrap.bundle.js" %}"></script>

    <script src="{% static "script.js" %}"></script>
  </body>
</html>

templates/search_form.html
<!-- _search_form.html -->
<form method="get" action="{% url 'shop:product_list' %}">
    <div class="row">
        <div class="col-5">
            {{ search_form.search_query }}
        </div>

        <div class="col-3">
            {{ search_form.search_category }}
        </div>

        <div class="col-2">
            <button type="submit" class="btn btn-success">Search</button>
        </div>
    </div>
</form> 