cart/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:p_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:p_id>/", views.cart_remove, name="cart_remove"),
]

data/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from .views import home
from . import views
from django.urls import path, include, re_path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", home, name="home"),
    path("account/", include("account.urls")),
    re_path(
        r"^account/account/$", RedirectView.as_view(url="/account/", permanent=True)
    ),
    path("orders/", include("orders.urls", namespace="orders")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("", include("shop.urls", namespace="shop")),
    # path('account/', views.account_details, name='account_details'),
]

payment/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = "payment"

urlpatterns = [
    path("process/", views.payment_process, name="process"),
    path("cod/", views.cash_on_delivery, name="cod"),
    path(
        "process_successded_cod/",
        views.process_successded_cod,
        name="process_successded_cod",
    ),
    path("already_processed/", views.already_processed, name="already_processed"),
    path(
        "process_successded/",
        views.process_successded,
        name="process_successded",
    ),
    path("completed/", views.payment_completed, name="completed"),
    path("canceled/", views.payment_canceled, name="canceled"),
    path("webhook/", webhooks.stripe_webhook, name="stripe-webhook"),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from decimal import Decimal
import stripe
from django.conf import settings
from django.shortcuts import (
    render,
    redirect,
    reverse,
    get_object_or_404,
    HttpResponseRedirect,
)
from orders.models import Order
from .tasks import payment_completed as payment_completed_task
from cart.cart import CartWrapper

# create the Stripe instance
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get("order_id", None)
    order = get_object_or_404(Order, id=order_id)
    if order.order_processed:
        return redirect("payment:already_processed")

    if request.method == "POST":
        success_url = request.build_absolute_uri(reverse("payment:completed"))
        cancel_url = request.build_absolute_uri(reverse("payment:canceled"))

        # Stripe checkout session data
        session_data = {
            "mode": "payment",
            "client_reference_id": order.id,
            "success_url": success_url,
            "cancel_url": cancel_url,
            "line_items": [],
        }
        # add order items to the Stripe checkout session
        for item in order.items.all():
            session_data["line_items"].append(
                {
                    "price_data": {
                        "unit_amount": int(item.price * Decimal("100")),
                        "currency": "EGP",
                        "product_data": {
                            "name": item.product.product_name,
                        },
                    },
                    "quantity": item.quantity,
                }
            )
        # Stripe coupon
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                name=order.coupon.code, percent_off=order.discount, duration="once"
            )
            session_data["discounts"] = [{"coupon": stripe_coupon.id}]
        # create Stripe checkout session
        session = stripe.checkout.Session.create(**session_data)

        # redirect to Stripe payment form
        return redirect(session.url, code=303)

    else:
        return render(request, "payment/process.html", locals())


def cash_on_delivery(request):
    order_id = request.session.get("order_id", None)
    order = get_object_or_404(Order, id=order_id)
    if order.order_processed:
        return redirect("payment:already_processed")
    cart = CartWrapper(request.user)
    if order_id and not order.paid:
        order.paid = False
        order.order_processed = True
        order.save()
        payment_completed_task(order_id)
        cart.clear()
    return redirect("payment:process_successded_cod")


def payment_completed(request):
    order_id = request.session.get("order_id", None)
    order = get_object_or_404(Order, id=order_id)
    if order.order_processed:
        return redirect("payment:already_processed")
    cart = CartWrapper(request.user)
    print(order.paid)
    print(order.order_processed)
    if order_id and not order.paid:
        order.paid = True
        order.order_processed = True
        order.save()
        payment_completed_task(order_id)
        cart.clear()
        return redirect("payment:process_successded")
    return redirect("payment:canceled")


def process_successded(request):
    return render(request, "payment/completed.html")


def process_successded_cod(request):
    return render(request, "payment/completed_cod.html")


def payment_canceled(request):
    return render(request, "payment/canceled.html")


def already_processed(request):
    return render(request, "payment/already_processed.html")

templates/payment/already_processed.html
{% extends "base.html" %}

{% block title %}
    Order Already Processed
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="alert alert-warning" role="alert">
                    <h4 class="alert-heading">Order Already Processed!</h4>
                    <p>This order has already been successfully processed. If you have any concerns, please contact customer support.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/payment/canceled.html
{% extends "base.html" %}

{% block title %}Payment canceled{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card text-center">
                    <div class="card-header">
                        <h1 class="display-4">Your payment has not been processed</h1>
                    </div>
                    <div class="card-body">
                        <p class="lead">There was a problem processing your payment.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/payment/completed.html
{% extends "base.html" %}

{% block title %}
    Payment successful
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card text-center">
                    <div class="card-header">
                        <h1 class="display-4">Your payment was successful</h1>
                    </div>
                    <div class="card-body">
                        <p class="lead">Your payment has been processed successfully.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/payment/completed_cod.html
{% extends "base.html" %}

{% block title %}
    Payment successful
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card text-center">
                    <div class="card-header">
                        <h1 class="display-4">Your order has been placed successfully</h1>
                    </div>
                    <div class="card-body">
                        <p class="lead">You have to pay on delivery.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/payment/process.html
{% extends "base.html" %}
{% load static %}
{% load mathfilters %}


{% block title %}Pay your order{% endblock %}

{% block content %}
  <h1>Order summary</h1>
  <table class="cart table table-striped">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      {% for item in order.items.all %}
        <tr>
          <td>
            <a href="{{ item.product.get_absolute_url }}">
              <img style="max-height: 100px;" src="{% if item.product.p_image %}{{ item.product.p_image }}
              {% else %}{% static "img/no_image.png" %}{% endif %}">
            </a>
          </td>
          <td>{{ item.product.product_name }}</td>
          <td class="num">{{ item.quantity }}</td>
          <td class="num">
            {% if item.product.discount %}
              EGP {{ item.product.discounted_price|floatformat:2 }}
            {% else %}
              EGP {{ item.price|floatformat:2 }}
            {% endif %}
          </td>
          <td class="num">EGP {{ item.get_cost | floatformat:2 }}</td>
        </tr>
      {% endfor %}
      {% if order.coupon %}
        <tr class="subtotal">
          <td>Subtotal</td>
          <td colspan="3"></td>
          <td class="num">
            EGP{{ order.get_total_cost_before_discount|floatformat:2 }}
          </td>
        </tr>
        <tr>
          <td>
            "{{ order.coupon.code }}" coupon
            ({{ order.discount }}% off)
          </td>
          <td colspan="3"></td>
          <td class="num neg">
            - EGP{{ order.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>Total</td>
        <td colspan="3"></td>
        <td class="num">
          EGP {{ order.get_total_cost|floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>

  <div class="d-inline">
    <form action="{% url 'payment:cod' %}" method="post" class="d-inline">
      <input class="btn btn-primary" type="submit" value="Pay on Delivery">
      {% csrf_token %}
    </form>

    <form action="{% url 'payment:process' %}" method="post" class="d-inline">
      <input class="btn btn-primary" type="submit" value="Pay now">
      {% csrf_token %}
    </form>
  </div>

{% endblock %}